package squad.ftt.gui;

import java.awt.Image;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import squad.ftt.adapters.ArticlesAdapter;
import squad.ftt.adapters.ChoixArticlesAdapter;
import squad.ftt.adapters.ChoixJoueurAdapter;
import squad.ftt.adapters.ChoixStadeAdapter;
import squad.ftt.dao.classes.ArticlesDao;
import squad.ftt.entities.Articles;



 
/**
 *
 * @author Rached
 */
public class AffichageArticles extends javax.swing.JFrame {
  int i = 0;
  public static boolean Livraison;
  public static Float total;
  public static List<Articles> arts;
  public AffichageArticles() {
           
        
        initComponents();  
            ChoixArticlesAdapter joueurAdapter=new ChoixArticlesAdapter();      
            DefaultTableModel mJoueur =(DefaultTableModel) articlesTab.getModel();
            Vector column_name=new Vector();
            Vector data_row;        
            for (int i=0 ; i<joueurAdapter.getColumnCount();i++){
              column_name.addElement(joueurAdapter.getColumnName(i));
              mJoueur.setColumnIdentifiers(column_name);}  
              for ( int k=0 ; k<joueurAdapter.getRowCount();k++)
                   {
                    data_row=new Vector();
                    data_row.addElement(joueurAdapter.getValueAt(k,1));
                    data_row.addElement(joueurAdapter.getValueAt(k,2));
                    data_row.addElement(joueurAdapter.getValueAt(k,3));
                    data_row.addElement(Boolean.FALSE);
                       mJoueur.addRow(data_row);
                    }
                      articlesTab.setModel(mJoueur); 
                   
        
    }      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prix = new javax.swing.JLabel();
        Total = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        prix1 = new javax.swing.JLabel();
        Total1 = new javax.swing.JLabel();
        colis = new javax.swing.JCheckBox();
        valider = new javax.swing.JButton();
        tableau = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        articlesTab = new javax.swing.JTable();
        Actualite = new javax.swing.JLabel();
        Joueurs = new javax.swing.JLabel();
        Match = new javax.swing.JLabel();
        Club = new javax.swing.JLabel();
        Tournoi = new javax.swing.JLabel();
        MatchAmicale = new javax.swing.JLabel();
        Stade = new javax.swing.JLabel();
        GestionDopage = new javax.swing.JLabel();
        Concours = new javax.swing.JLabel();
        Formation5 = new javax.swing.JLabel();
        article = new javax.swing.JLabel();
        Fond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        prix.setFont(new java.awt.Font("Urdu Typesetting", 0, 18)); // NOI18N
        prix.setForeground(new java.awt.Color(255, 255, 255));
        prix.setText("00.00");
        getContentPane().add(prix);
        prix.setBounds(360, 530, 90, 50);

        Total.setFont(new java.awt.Font("Urdu Typesetting", 0, 18)); // NOI18N
        Total.setForeground(new java.awt.Color(255, 255, 0));
        Total.setText("Total Panier : ");
        getContentPane().add(Total);
        Total.setBounds(250, 530, 120, 50);
        getContentPane().add(image);
        image.setBounds(900, 180, 280, 310);

        prix1.setFont(new java.awt.Font("Urdu Typesetting", 0, 18)); // NOI18N
        prix1.setForeground(new java.awt.Color(255, 255, 255));
        prix1.setText("10DT");
        getContentPane().add(prix1);
        prix1.setBounds(350, 490, 90, 50);

        Total1.setFont(new java.awt.Font("Urdu Typesetting", 0, 18)); // NOI18N
        Total1.setForeground(new java.awt.Color(255, 255, 0));
        Total1.setText("Collissimo:");
        getContentPane().add(Total1);
        Total1.setBounds(250, 490, 120, 50);

        colis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colisActionPerformed(evt);
            }
        });
        getContentPane().add(colis);
        colis.setBounds(440, 510, 20, 20);

        valider.setText("Valider Panier");
        valider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                validerMouseClicked(evt);
            }
        });
        valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerActionPerformed(evt);
            }
        });
        getContentPane().add(valider);
        valider.setBounds(440, 540, 180, 40);

        articlesTab.setModel(new javax.swing.table.DefaultTableModel(

        ));
        articlesTab = new JTable(articlesTab.getModel()) {
            @Override
            public Class getColumnClass(int column) {
                switch (column) {
                    case 0:
                    return String.class;

                    case 1:
                    return String.class;

                    case 2:
                    return String.class;
                    case 3:
                    return Boolean.class;

                    default:
                    return String.class;
                }
            }
        };
        articlesTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                articlesTabMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(articlesTab);
        {

        };

        tableau.addTab("Articles    ", jScrollPane1);

        getContentPane().add(tableau);
        tableau.setBounds(250, 160, 530, 330);

        Actualite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ActualiteMouseClicked(evt);
            }
        });
        getContentPane().add(Actualite);
        Actualite.setBounds(0, 120, 210, 40);

        Joueurs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JoueursMouseClicked(evt);
            }
        });
        getContentPane().add(Joueurs);
        Joueurs.setBounds(0, 160, 200, 40);

        Match.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MatchMouseClicked(evt);
            }
        });
        getContentPane().add(Match);
        Match.setBounds(0, 210, 200, 40);

        Club.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClubMouseClicked(evt);
            }
        });
        getContentPane().add(Club);
        Club.setBounds(0, 260, 200, 40);

        Tournoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TournoiMouseClicked(evt);
            }
        });
        getContentPane().add(Tournoi);
        Tournoi.setBounds(0, 310, 200, 40);

        MatchAmicale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MatchAmicaleMouseClicked(evt);
            }
        });
        getContentPane().add(MatchAmicale);
        MatchAmicale.setBounds(0, 360, 200, 40);

        Stade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StadeMouseClicked(evt);
            }
        });
        getContentPane().add(Stade);
        Stade.setBounds(0, 410, 200, 40);

        GestionDopage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GestionDopageMouseClicked(evt);
            }
        });
        getContentPane().add(GestionDopage);
        GestionDopage.setBounds(0, 450, 200, 40);

        Concours.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConcoursMouseClicked(evt);
            }
        });
        getContentPane().add(Concours);
        Concours.setBounds(0, 500, 210, 40);

        Formation5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Formation5MouseClicked(evt);
            }
        });
        getContentPane().add(Formation5);
        Formation5.setBounds(0, 540, 210, 40);
        getContentPane().add(article);
        article.setBounds(0, 590, 210, 30);

        Fond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/squad/ftt/images/Produit1.jpg"))); // NOI18N
        getContentPane().add(Fond);
        Fond.setBounds(0, -10, 1260, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void articlesTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_articlesTabMouseClicked
    List<Articles> articles = new ArrayList<>();
    ChoixArticlesAdapter articleAdapter=new ChoixArticlesAdapter();  
    ArticlesDao aDao = new ArticlesDao();
    arts= new ArrayList<>();
   ImageIcon imgIcon = new ImageIcon("C:\\wamp\\www\\SquadWeb\\web\\uploads\\"+articleAdapter.articles.get(articlesTab.getSelectedRow()).getImg_article());
   Image img1 = imgIcon.getImage();
   Image img2 = img1.getScaledInstance(image.getWidth(), image.getHeight(), Image.SCALE_SMOOTH);
   image.setIcon(new ImageIcon(img2));
    Articles a;
    
    
    
    float p =0;    
    for( int i=0; i<articlesTab.getRowCount();i++)
    {      
        if((Boolean) articlesTab.getValueAt(i,3))
        {
            a=new Articles();
            arts.add(aDao.findArticleById((int) articleAdapter.getValueAt(i, 0)));
        p=p+ (Float)articlesTab.getValueAt(i,2);
        }
    }
    if(colis.isSelected())
        {  p=p+10.0F;
        i=1;     
      }
        if(i==1 && colis.isSelected()==false )
        {
        p=p-10.0F;
        i=0;
        }
        prix.setText( String.valueOf(p )  );
       
     
    }//GEN-LAST:event_articlesTabMouseClicked

    private void validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerActionPerformed
        Livraison = colis.isSelected() ;
        total= Float.valueOf(prix.getText());
        ConfirmAchat p = new ConfirmAchat();
        
    }//GEN-LAST:event_validerActionPerformed

    private void colisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colisActionPerformed
      Float somme = Float.parseFloat(prix.getText());  
      Float p =0.0F;
    
      if(colis.isSelected() && i==0)
        {  p=10.0F;
        i=1;     
      }
        if(i==1 && colis.isSelected()==false )
        {
        p=-10.0F;
        i=0;
        }
        prix.setText( String.valueOf(somme+p )  );
        
        
    }//GEN-LAST:event_colisActionPerformed

    private void validerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_validerMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_validerMouseClicked

    private void ActualiteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActualiteMouseClicked

        this.dispose();
        AffichageActualite ge = new AffichageActualite();
        ge.setSize(1220, 655);
                ge.setVisible(true);

    }//GEN-LAST:event_ActualiteMouseClicked

    private void JoueursMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JoueursMouseClicked
        this.dispose();
        GestionJoueurs ge = new GestionJoueurs();
        ge.setSize(1220, 655);
        ge.setVisible(true);
    }//GEN-LAST:event_JoueursMouseClicked

    private void MatchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MatchMouseClicked
        this.dispose();
        GestionMatchs ge = new GestionMatchs();
        ge.setSize(1220, 655);
        ge.setVisible(true);
    }//GEN-LAST:event_MatchMouseClicked

    private void ClubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClubMouseClicked
        this.dispose();
        GestionClub ge = new GestionClub();
        ge.setSize(1220, 655);
        ge.setVisible(true);
    }//GEN-LAST:event_ClubMouseClicked

    private void TournoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TournoiMouseClicked
        this.dispose();
        GestionEvenement ge = new  GestionEvenement();
        ge.setSize(1220, 655);
        ge.setVisible(true);
    }//GEN-LAST:event_TournoiMouseClicked

    private void MatchAmicaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MatchAmicaleMouseClicked
        this.dispose();
        GestionArbitre ge = new GestionArbitre();
        ge.setSize(1220, 655);
        ge.setVisible(true);
    }//GEN-LAST:event_MatchAmicaleMouseClicked

    private void StadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StadeMouseClicked
        this.dispose();
        GestionStade ge = new GestionStade();
        ge.setSize(1220, 655);
                ge.setVisible(true);

    }//GEN-LAST:event_StadeMouseClicked

    private void GestionDopageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GestionDopageMouseClicked
        this.dispose();
        GestionDopage ge = new GestionDopage();
        ge.setSize(1220, 655);
                ge.setVisible(true);

    }//GEN-LAST:event_GestionDopageMouseClicked

    private void ConcoursMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConcoursMouseClicked
        this.dispose();
        GestionConcours ge = new GestionConcours();
        ge.setSize(1220, 655);
                ge.setVisible(true);

    }//GEN-LAST:event_ConcoursMouseClicked

    private void Formation5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Formation5MouseClicked
      try {
          this.dispose();
          GestionFormation ge = new GestionFormation();
          ge.setSize(1220, 655);
          ge.setVisible(true);
      } catch (Exception ex) {
          Logger.getLogger(AffichageArticles.class.getName()).log(Level.SEVERE, null, ex);
      }

    }//GEN-LAST:event_Formation5MouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AffichageArticles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AffichageArticles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AffichageArticles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AffichageArticles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AffichageArticles ge = new AffichageArticles();
                ge.setSize(1220, 665);
                ge.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Actualite;
    private javax.swing.JLabel Club;
    private javax.swing.JLabel Concours;
    private javax.swing.JLabel Fond;
    private javax.swing.JLabel Formation5;
    private javax.swing.JLabel GestionDopage;
    private javax.swing.JLabel Joueurs;
    private javax.swing.JLabel Match;
    private javax.swing.JLabel MatchAmicale;
    private javax.swing.JLabel Stade;
    private javax.swing.JLabel Total;
    private javax.swing.JLabel Total1;
    private javax.swing.JLabel Tournoi;
    private javax.swing.JLabel article;
    private javax.swing.JTable articlesTab;
    private javax.swing.JCheckBox colis;
    private javax.swing.JLabel image;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel prix;
    private javax.swing.JLabel prix1;
    private javax.swing.JTabbedPane tableau;
    private javax.swing.JButton valider;
    // End of variables declaration//GEN-END:variables
}
