/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package squad.ftt.gui;

import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import squad.ftt.dao.classes.UtilisateurDao;
import squad.ftt.entities.Utilisateur;

/**
 *
 * @author hp
 */
public class Authentification extends javax.swing.JFrame {
    private Object rs;
     public static   Utilisateur user = new Utilisateur();

    /**
     * Creates new form Authentification
     */
    public Authentification() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butt_fb = new javax.swing.JButton();
        button_login = new javax.swing.JButton();
        butt_redirect_insc = new javax.swing.JButton();
        txt_login = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        butt_fb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/squad/ftt/images/fdsfs.jpg"))); // NOI18N
        butt_fb.setToolTipText("");
        getContentPane().add(butt_fb, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 450, 230, 50));

        button_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/squad/ftt/images/sign up button.jpg"))); // NOI18N
        button_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_loginActionPerformed(evt);
            }
        });
        getContentPane().add(button_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 350, 250, 40));

        butt_redirect_insc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/squad/ftt/images/sign in button.jpg"))); // NOI18N
        butt_redirect_insc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt_redirect_inscActionPerformed(evt);
            }
        });
        getContentPane().add(butt_redirect_insc, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 400, 250, 40));
        getContentPane().add(txt_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 245, 200, 30));

        txt_password.setText("jPasswordField1");
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 300, 200, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/squad/ftt/images/auth copy.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(960, 640));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_loginActionPerformed
        UtilisateurDao ud = new UtilisateurDao();
        user=null;
        try {
            user = ud.findAuthen(txt_login.getText(), txt_password.getText());
        } catch (SQLException ex) {
            Logger.getLogger(Authentification.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Authentification.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(user==null)
        {     JOptionPane.showMessageDialog(null,"Veuillez vérifier vos identifiants ");
        }
        else if (user.getRole().equals("admin"))
                {
                GestionEvenement ge = new GestionEvenement();
                ge.setSize(1220, 665);
                ge.setVisible(true);

                }
        else if (user.getRole().equals("fan")  )
        {      GestionUtilisateurs ge = new GestionUtilisateurs();
                ge.setSize(1220, 665);
                ge.setVisible(true);
        }
        else if (user.getRole().equals("responsable"))
        {
        //
        }   
    }//GEN-LAST:event_button_loginActionPerformed

    private void butt_redirect_inscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt_redirect_inscActionPerformed
        Inscription ins =new Inscription();
        ins.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_butt_redirect_inscActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Authentification().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butt_fb;
    private javax.swing.JButton butt_redirect_insc;
    private javax.swing.JButton button_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txt_login;
    private javax.swing.JPasswordField txt_password;
    // End of variables declaration//GEN-END:variables
}
