/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package squad.ftt.gui;

import java.awt.Dimension;
import java.io.File;
import java.io.IOException;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import squad.ftt.adapters.PostulationAdapter;
import squad.ftt.adapters.PostulationFormationAdapter;
import squad.ftt.dao.classes.DisponibiliteDao;
import squad.ftt.dao.classes.FormationDao;
import squad.ftt.dao.classes.PostulationDao;
import squad.ftt.dao.classes.UtilisateurDao;
import squad.ftt.dao.classes.concoursDAO;
import squad.ftt.entities.Disponibiliter;
import squad.ftt.entities.Formation;
import squad.ftt.entities.Postulation;

/**
 *
 * @author esprit
 */
public class GestionArbitre extends javax.swing.JFrame {

    /**
     * Creates new form GestionEvenement
     */
    public GestionArbitre() {
        try {

            try {

                initComponents();
                PostulationFormationAdapter postulationAdapter = new PostulationFormationAdapter();
                DefaultTableModel model;
                model = (DefaultTableModel) jTablePostFormation.getModel();

                Vector column_name = new Vector();
                Vector data_row = new Vector();
                System.out.println("aaaaa");
                for (int i = 0; i < postulationAdapter.getColumnCount(); i++) {
                    column_name.addElement(postulationAdapter.getColumnName(i));
                    model.setColumnIdentifiers(column_name);
                }
                for (int k = 0; k < postulationAdapter.getRowCount(); k++) {
                    data_row = new Vector();
                    data_row.addElement(postulationAdapter.getValueAt(k, 0));
                    data_row.addElement(postulationAdapter.getValueAt(k, 1));
                    data_row.addElement(postulationAdapter.getValueAt(k, 2));
                    data_row.addElement(postulationAdapter.getValueAt(k, 3));
                    data_row.addElement(postulationAdapter.getValueAt(k, 4));
                    data_row.addElement(postulationAdapter.getValueAt(k, 5));
                    data_row.addElement(postulationAdapter.getValueAt(k, 6));
                    data_row.addElement(postulationAdapter.getValueAt(k, 7));
                    data_row.addElement(postulationAdapter.getValueAt(k, 8));

                    model.addRow(data_row);
                }
                jTablePostFormation.setModel(model);
            } catch (Exception ex) {
                Logger.getLogger(GestionArbitre.class.getName()).log(Level.SEVERE, null, ex);
            }
            PostulationAdapter postulationAdapter = new PostulationAdapter();
            DefaultTableModel model = (DefaultTableModel) jTablePostConcours.getModel();
            Vector column_name = new Vector();
            Vector data_row = new Vector();
            System.out.println("aaaaa");
            for (int i = 0; i < postulationAdapter.getColumnCount(); i++) {
                column_name.addElement(postulationAdapter.getColumnName(i));
                model.setColumnIdentifiers(column_name);
            }
            for (int k = 0; k < postulationAdapter.getRowCount(); k++) {
                data_row = new Vector();
                data_row.addElement(postulationAdapter.getValueAt(k, 0));
                data_row.addElement(postulationAdapter.getValueAt(k, 1));
                data_row.addElement(postulationAdapter.getValueAt(k, 2));
                data_row.addElement(postulationAdapter.getValueAt(k, 3));
                data_row.addElement(postulationAdapter.getValueAt(k, 4));
                data_row.addElement(postulationAdapter.getValueAt(k, 5));

                model.addRow(data_row);
            }
            jTablePostConcours.setModel(model);

        } catch (IOException ex) {
            Logger.getLogger(GestionArbitre.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        affichage = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Actualite = new javax.swing.JLabel();
        Joueurs = new javax.swing.JLabel();
        Match = new javax.swing.JLabel();
        Club = new javax.swing.JLabel();
        Tournoi = new javax.swing.JLabel();
        MatchAmicale = new javax.swing.JLabel();
        GestionDopage = new javax.swing.JLabel();
        Stade = new javax.swing.JLabel();
        Concours = new javax.swing.JLabel();
        Formation5 = new javax.swing.JLabel();
        article = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jCalendar = new com.toedter.calendar.JCalendar();
        jLabel15 = new javax.swing.JLabel();
        confirmer = new javax.swing.JButton();
        annuler = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        cin = new javax.swing.JTextField();
        resultat = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        cv11 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePostFormation = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        postuler1 = new javax.swing.JButton();
        annuler1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePostConcours = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        postuler2 = new javax.swing.JButton();
        annuler2 = new javax.swing.JButton();
        Fond = new javax.swing.JLabel();

        jFrame1.getContentPane().setLayout(null);
        jFrame1.getContentPane().add(affichage);
        affichage.setBounds(20, 14, 350, 60);

        jButton2.setText("confirmer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jButton2);
        jButton2.setBounds(50, 140, 77, 23);

        jButton3.setText("annuler");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jButton3);
        jButton3.setBounds(220, 140, 69, 23);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Actualite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ActualiteMouseClicked(evt);
            }
        });
        getContentPane().add(Actualite);
        Actualite.setBounds(0, 120, 210, 40);

        Joueurs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JoueursMouseClicked(evt);
            }
        });
        getContentPane().add(Joueurs);
        Joueurs.setBounds(0, 160, 200, 40);

        Match.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MatchMouseClicked(evt);
            }
        });
        getContentPane().add(Match);
        Match.setBounds(0, 210, 200, 40);

        Club.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClubMouseClicked(evt);
            }
        });
        getContentPane().add(Club);
        Club.setBounds(0, 260, 200, 40);

        Tournoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TournoiMouseClicked(evt);
            }
        });
        getContentPane().add(Tournoi);
        Tournoi.setBounds(0, 310, 200, 40);

        MatchAmicale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MatchAmicaleMouseClicked(evt);
            }
        });
        getContentPane().add(MatchAmicale);
        MatchAmicale.setBounds(0, 360, 200, 40);

        GestionDopage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GestionDopageMouseClicked(evt);
            }
        });
        getContentPane().add(GestionDopage);
        GestionDopage.setBounds(0, 450, 200, 40);

        Stade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StadeMouseClicked(evt);
            }
        });
        getContentPane().add(Stade);
        Stade.setBounds(0, 410, 200, 40);

        Concours.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConcoursMouseClicked(evt);
            }
        });
        getContentPane().add(Concours);
        Concours.setBounds(0, 500, 210, 40);

        Formation5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Formation5MouseClicked(evt);
            }
        });
        getContentPane().add(Formation5);
        Formation5.setBounds(0, 540, 210, 40);
        getContentPane().add(article);
        article.setBounds(0, 590, 210, 30);

        jTabbedPane1.setForeground(new java.awt.Color(0, 51, 204));
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jPanel3.setLayout(null);
        jPanel3.add(jLabel13);
        jLabel13.setBounds(482, 5, 0, 0);

        jLabel14.setForeground(new java.awt.Color(51, 0, 204));
        jLabel14.setText("Disponibilité:");
        jLabel14.setMaximumSize(new java.awt.Dimension(60, 30));
        jPanel3.add(jLabel14);
        jLabel14.setBounds(10, 20, 80, 20);

        jCalendar.setForeground(new java.awt.Color(51, 0, 255));
        jCalendar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jCalendarPropertyChange(evt);
            }
        });
        jPanel3.add(jCalendar);
        jCalendar.setBounds(110, 80, 620, 270);

        jLabel15.setFont(new java.awt.Font("Source Code Pro", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 204));
        jLabel15.setText("Choisissez votre date d'empechement!");
        jLabel15.setPreferredSize(new java.awt.Dimension(185, 140));
        jPanel3.add(jLabel15);
        jLabel15.setBounds(200, 40, 490, 30);

        confirmer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        confirmer.setText("Confirmer");
        jPanel3.add(confirmer);
        confirmer.setBounds(260, 410, 110, 25);

        annuler.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        annuler.setText("Annuler");
        jPanel3.add(annuler);
        annuler.setBounds(460, 410, 100, 25);

        jLabel16.setText("entrer votre cin:");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(10, 380, 160, 14);
        jPanel3.add(cin);
        cin.setBounds(20, 420, 110, 20);
        jPanel3.add(resultat);
        resultat.setBounds(210, 460, 330, 20);

        jTabbedPane1.addTab("Disponibilite", jPanel3);

        jPanel5.setLayout(null);

        jLabel2.setText("Ancienneté");
        jPanel5.add(jLabel2);
        jLabel2.setBounds(10, 180, 90, 14);

        jLabel4.setText("Nombre de matchs:");
        jPanel5.add(jLabel4);
        jLabel4.setBounds(10, 220, 100, 14);

        jLabel5.setText("Poster votre cv:");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(10, 260, 80, 14);

        jLabel6.setText("cin:");
        jPanel5.add(jLabel6);
        jLabel6.setBounds(10, 300, 110, 14);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField1);
        jTextField1.setBounds(170, 180, 150, 20);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField2);
        jTextField2.setBounds(170, 220, 150, 20);

        cv11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cv11ActionPerformed(evt);
            }
        });
        jPanel5.add(cv11);
        cv11.setBounds(170, 260, 150, 20);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField4);
        jTextField4.setBounds(170, 300, 150, 20);

        jTablePostFormation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Libelle", "Grade", "Nom", "DateDebutFormation", "DateFinForation", "dateDebPostulation", "DateFinPost", "Frais"
            }
        ));
        jTablePostFormation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePostFormationMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePostFormation);

        jPanel5.add(jScrollPane1);
        jScrollPane1.setBounds(10, 30, 930, 90);

        jButton1.setText("Parcourir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1);
        jButton1.setBounds(360, 260, 90, 23);

        postuler1.setText("Postuler");
        postuler1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postuler1ActionPerformed(evt);
            }
        });
        jPanel5.add(postuler1);
        postuler1.setBounds(110, 420, 90, 23);

        annuler1.setText("Annuler");
        annuler1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annuler1ActionPerformed(evt);
            }
        });
        jPanel5.add(annuler1);
        annuler1.setBounds(250, 420, 100, 23);

        jTabbedPane1.addTab("Postuler pour une formation ", jPanel5);

        jPanel4.setLayout(null);

        jTablePostConcours.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "libelle_concour", "date_debut_concour", "lieu_concour", "description_concours", "frais_participation", "date_debut_depot", "date_fin_depot", "type_concour"
            }
        ));
        jScrollPane2.setViewportView(jTablePostConcours);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(20, 10, 770, 90);

        jLabel8.setText("Ancienneté");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(20, 170, 60, 14);

        jLabel9.setText("NombreDEmatchs");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(20, 210, 90, 20);

        jLabel10.setText("Poster votre CV:");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(20, 250, 90, 14);

        jLabel11.setText("cin");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(20, 290, 13, 14);
        jPanel4.add(jTextField5);
        jTextField5.setBounds(120, 170, 100, 20);
        jPanel4.add(jTextField6);
        jTextField6.setBounds(120, 210, 100, 20);
        jPanel4.add(jTextField7);
        jTextField7.setBounds(120, 250, 100, 20);
        jPanel4.add(jTextField8);
        jTextField8.setBounds(120, 290, 100, 20);

        jButton4.setText("Parcourir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4);
        jButton4.setBounds(270, 250, 100, 23);

        postuler2.setText("Postuler");
        postuler2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postuler2ActionPerformed(evt);
            }
        });
        jPanel4.add(postuler2);
        postuler2.setBounds(70, 440, 71, 23);

        annuler2.setText("Annuler");
        jPanel4.add(annuler2);
        annuler2.setBounds(220, 440, 69, 23);

        jTabbedPane1.addTab("Postuler pour un concours", jPanel4);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(230, 80, 970, 550);

        Fond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/squad/ftt/images/arbitre1.jpg"))); // NOI18N
        getContentPane().add(Fond);
        Fond.setBounds(0, -10, 1260, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ActualiteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActualiteMouseClicked

        this.dispose();
        AffichageActualite ge = new AffichageActualite();
        ge.setSize(1220, 655);
        ge.setVisible(true);

    }//GEN-LAST:event_ActualiteMouseClicked

    private void JoueursMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JoueursMouseClicked
        this.dispose();
        GestionJoueurs ge = new GestionJoueurs();
        ge.setSize(1220, 655);
        ge.setVisible(true);
    }//GEN-LAST:event_JoueursMouseClicked

    private void MatchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MatchMouseClicked
        this.dispose();
        GestionMatchs ge = new GestionMatchs();
        ge.setSize(1220, 655);
        ge.setVisible(true);
    }//GEN-LAST:event_MatchMouseClicked

    private void ClubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClubMouseClicked
        this.dispose();
        GestionClub ge = new GestionClub();
        ge.setSize(1220, 655);
        ge.setVisible(true);
    }//GEN-LAST:event_ClubMouseClicked

    private void TournoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TournoiMouseClicked
        this.dispose();
        GestionEvenement ge = new GestionEvenement();
        ge.setSize(1220, 655);
        ge.setVisible(true);
    }//GEN-LAST:event_TournoiMouseClicked

    private void MatchAmicaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MatchAmicaleMouseClicked
        this.dispose();
        GestionArbitre ge = new GestionArbitre();
        ge.setSize(1220, 655);
        ge.setVisible(true);
    }//GEN-LAST:event_MatchAmicaleMouseClicked

    private void GestionDopageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GestionDopageMouseClicked
        this.dispose();
        GestionDopage ge = new GestionDopage();
        ge.setSize(1220, 655);
        ge.setVisible(true);

    }//GEN-LAST:event_GestionDopageMouseClicked

    private void StadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StadeMouseClicked
        this.dispose();
        GestionStade ge = new GestionStade();
        ge.setSize(1220, 655);
        ge.setVisible(true);

    }//GEN-LAST:event_StadeMouseClicked

    private void ConcoursMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConcoursMouseClicked
        this.dispose();
        GestionConcours ge = new GestionConcours();
        ge.setSize(1220, 655);
        ge.setVisible(true);

    }//GEN-LAST:event_ConcoursMouseClicked

    private void Formation5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Formation5MouseClicked
        this.dispose();
        //GestionFormation ge = new GestionFormation();
        // ge.setSize(1220, 655);
        // ge.setVisible(true);
    }//GEN-LAST:event_Formation5MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void cv11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cv11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cv11ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser cv1 = new JFileChooser();
        //  cv1.setAcceptAllFileFilterUsed(false);
        // FileNameExtensionFilter filter = new FileNameExtensionFilter("pdf");
        // cv1.addChoosableFileFilter(filter);
        cv1.showOpenDialog(null);
        File fNaiss = cv1.getSelectedFile();
        String filename = fNaiss.getAbsolutePath();
        cv11.setText(filename);

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void postuler1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postuler1ActionPerformed
        try {

            PostulationDao postulation = new PostulationDao();
            Postulation p = new Postulation();
            FormationDao cd = new FormationDao();
            UtilisateurDao ad = new UtilisateurDao();
            p.setAnciennete(Integer.parseInt(jTextField1.getText()));
            p.setNbre_match(Integer.parseInt(jTextField2.getText()));
            p.setCv_arbitre(cv11.getText());
            p.setUser(ad.findUserById(Integer.parseInt(jTextField4.getText())));
            DefaultTableModel model = (DefaultTableModel) jTablePostFormation.getModel();
            p.setFormation_id_Formation((int) model.getValueAt(jTablePostFormation.getSelectedRow(), 0));

            postulation.ajouterPostulationFormation(p);

        } catch (IOException ex) {
            Logger.getLogger(GestionArbitre.class.getName()).log(Level.SEVERE, null, ex);
        }

// TODO add your handling code here:
    }//GEN-LAST:event_postuler1ActionPerformed

    private void annuler1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annuler1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_annuler1ActionPerformed
    String ab = " ";
    private void jCalendarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jCalendarPropertyChange

        SimpleDateFormat format1 = new SimpleDateFormat("yyyy-MM-dd");
        if (!format1.format(jCalendar.getDate()).equals(format1.format(new java.util.Date()))) {
            jFrame1.setSize(400, 300);
            jFrame1.setVisible(true);

            ab = (String) format1.format(jCalendar.getDate());
            affichage.setText("êtes vous in able pour le " + ab);

        }

// TODO add your handling code here:
    }//GEN-LAST:event_jCalendarPropertyChange

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jFrame1.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:

// TODO add your handling code here:
        DisponibiliteDao dispo = new DisponibiliteDao();
        Disponibiliter d = new Disponibiliter();
        UtilisateurDao ad = new UtilisateurDao();
        d.setUser(ad.findUserById(Integer.parseInt(cin.getText())));
        d.setDate_empechement(Date.valueOf(ab));
        jFrame1.setVisible(false);
        dispo.addDisponibilite(d);
        resultat.setText("Date ajoutée avec succés!");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTablePostFormationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePostFormationMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_jTablePostFormationMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        JFileChooser cv1 = new JFileChooser();
        //  cv1.setAcceptAllFileFilterUsed(false);
        // FileNameExtensionFilter filter = new FileNameExtensionFilter("pdf");
        // cv1.addChoosableFileFilter(filter);
        cv1.showOpenDialog(null);
        File fNaiss = cv1.getSelectedFile();
        String filename = fNaiss.getAbsolutePath();
        jTextField7.setText(filename);// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void postuler2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postuler2ActionPerformed
 try {

            PostulationDao postulation = new PostulationDao();
            Postulation p = new Postulation();
            concoursDAO cd = new concoursDAO();
            UtilisateurDao ad = new UtilisateurDao();
            p.setAnciennete(Integer.parseInt(jTextField5.getText()));
            p.setNbre_match(Integer.parseInt(jTextField6.getText()));
            p.setCv_arbitre(jTextField7.getText());
            p.setUser(ad.findUserById(Integer.parseInt(jTextField8.getText())));
            DefaultTableModel model = (DefaultTableModel) jTablePostConcours.getModel();
            p.setConcours_id_Concour((int) model.getValueAt(jTablePostConcours.getSelectedRow(), 0));

            postulation.ajouterPostulation(p);

        } catch (IOException ex) {
            Logger.getLogger(GestionArbitre.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_postuler2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionArbitre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionArbitre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionArbitre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionArbitre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GestionArbitre ge = new GestionArbitre();
                ge.setSize(1220, 665);
                ge.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Actualite;
    private javax.swing.JLabel Club;
    private javax.swing.JLabel Concours;
    private javax.swing.JLabel Fond;
    private javax.swing.JLabel Formation5;
    private javax.swing.JLabel GestionDopage;
    private javax.swing.JLabel Joueurs;
    private javax.swing.JLabel Match;
    private javax.swing.JLabel MatchAmicale;
    private javax.swing.JLabel Stade;
    private javax.swing.JLabel Tournoi;
    private javax.swing.JLabel affichage;
    private javax.swing.JButton annuler;
    private javax.swing.JButton annuler1;
    private javax.swing.JButton annuler2;
    private javax.swing.JLabel article;
    private javax.swing.JTextField cin;
    private javax.swing.JButton confirmer;
    private javax.swing.JTextField cv11;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private com.toedter.calendar.JCalendar jCalendar;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTablePostConcours;
    private javax.swing.JTable jTablePostFormation;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JButton postuler1;
    private javax.swing.JButton postuler2;
    private javax.swing.JLabel resultat;
    // End of variables declaration//GEN-END:variables
}
