    /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package squad.ftt.gui;

import java.awt.Dimension;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.MalformedURLException;
import java.net.URL;
import java.sql.Date;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import squad.ftt.adapters.EvenementAdapter;
import squad.ftt.dao.classes.EvenementDao;
import squad.ftt.dao.classes.TourDao;
import squad.ftt.dao.classes.UtilisateurDao;
import squad.ftt.entities.Evenement;
import squad.ftt.entities.Tour;
import squad.ftt.entities.Utilisateur;

/**
 *
 * @author esprit
 */
public class GestionEvenement extends javax.swing.JFrame {

    public static Evenement evenement;
    public static String filePath;
    private String imageNom;

    /**
     * Creates new form GestionEvenement
     */
    public GestionEvenement() {
        initComponents();

        EvenementAdapter stadeAdapter = new EvenementAdapter();
        DefaultTableModel model = (DefaultTableModel) Evenement_Tab.getModel();
        Vector column_name = new Vector();
        Vector data_row = new Vector();
        for (int i = 0; i < stadeAdapter.getColumnCount(); i++) {
            column_name.addElement(stadeAdapter.getColumnName(i));
            model.setColumnIdentifiers(column_name);
        }
        for (int k = 0; k < stadeAdapter.getRowCount(); k++) {
            data_row = new Vector();
            data_row.addElement(stadeAdapter.getValueAt(k, 1));
            data_row.addElement(stadeAdapter.getValueAt(k, 2));
            data_row.addElement(stadeAdapter.getValueAt(k, 3));
            data_row.addElement(stadeAdapter.getValueAt(k, 4));
            data_row.addElement(stadeAdapter.getValueAt(k, 5));
            data_row.addElement(stadeAdapter.getValueAt(k, 6));
            model.addRow(data_row);
        }
        Evenement_Tab.setModel(model);
    }

    public void filter(String query) {
        DefaultTableModel model = (DefaultTableModel) Evenement_Tab.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        Evenement_Tab.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(query));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Evenement_Tab = new javax.swing.JTable();
        libelleEvenement = new javax.swing.JTextField();
        type = new javax.swing.JComboBox();
        nbreJoueur = new javax.swing.JComboBox();
        site = new javax.swing.JComboBox();
        ajouter = new javax.swing.JButton();
        supprimer = new javax.swing.JButton();
        modifier = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        recherche = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ajoutImage = new javax.swing.JButton();
        dateDebut = new com.toedter.calendar.JDateChooser();
        dateFin = new com.toedter.calendar.JDateChooser();
        imageEvenement = new javax.swing.JLabel();
        imageName = new javax.swing.JTextField();
        details = new javax.swing.JButton();
        Actualite = new javax.swing.JLabel();
        Joueurs = new javax.swing.JLabel();
        Match = new javax.swing.JLabel();
        Club = new javax.swing.JLabel();
        Tournoi = new javax.swing.JLabel();
        MatchAmicale = new javax.swing.JLabel();
        GestionDopage = new javax.swing.JLabel();
        Stade = new javax.swing.JLabel();
        Concours = new javax.swing.JLabel();
        Formation8 = new javax.swing.JLabel();
        article = new javax.swing.JLabel();
        Fond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Evenement_Tab.setAutoCreateRowSorter(true);
        Evenement_Tab.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Evenement_Tab.setModel(new javax.swing.table.DefaultTableModel(

        ));
        Evenement_Tab.setAlignmentX(1.0F);
        Evenement_Tab.setAlignmentY(1.0F);
        Evenement_Tab.setFocusable(false);
        Evenement_Tab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Evenement_TabMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Evenement_Tab);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(240, 110, 590, 140);
        getContentPane().add(libelleEvenement);
        libelleEvenement.setBounds(410, 260, 150, 30);

        type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Single", "Double" }));
        getContentPane().add(type);
        type.setBounds(410, 380, 150, 30);

        nbreJoueur.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "4", "8", "16", "32","64" }));
        getContentPane().add(nbreJoueur);
        nbreJoueur.setBounds(410, 420, 150, 30);

        site.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ariana", "Béja", "Ben Arous", "Bizerte", "Gabès", "Gafsa", "Jendouba", "Kairouan", "Kasserine", "Kébili", "Le Kef", "Mahdia", "La Manouba", "Médenine", "Monastir", "Nabeul", "Sfax", "Sidi", "Siliana", "Sousse", "Tataouine", "Tozeur", "Tunis", "Zaghouan"  }));
        getContentPane().add(site);
        site.setBounds(410, 460, 150, 30);

        ajouter.setText("Ajouter");
        ajouter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajouterMouseClicked(evt);
            }
        });
        ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });
        getContentPane().add(ajouter);
        ajouter.setBounds(250, 560, 90, 30);

        supprimer.setText("Supprimer");
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });
        getContentPane().add(supprimer);
        supprimer.setBounds(470, 560, 90, 30);

        modifier.setText("Modifier");
        modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierActionPerformed(evt);
            }
        });
        getContentPane().add(modifier);
        modifier.setBounds(360, 560, 90, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Libelle Evenement");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(250, 260, 150, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("Date Debut");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(250, 300, 150, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("Date Fin");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(250, 340, 150, 30);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("Type");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(250, 380, 150, 30);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("Site");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(250, 460, 150, 30);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("Image Evenement");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(250, 500, 150, 30);

        recherche.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rechercheKeyReleased(evt);
            }
        });
        getContentPane().add(recherche);
        recherche.setBounds(270, 10, 230, 30);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 0));
        jLabel9.setText("Nombre Joueurs");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(250, 420, 150, 30);

        ajoutImage.setText("Parcourir");
        ajoutImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutImageActionPerformed(evt);
            }
        });
        getContentPane().add(ajoutImage);
        ajoutImage.setBounds(570, 500, 150, 30);

        dateDebut.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(dateDebut);
        dateDebut.setBounds(410, 300, 150, 30);

        dateFin.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(dateFin);
        dateFin.setBounds(410, 340, 150, 30);
        getContentPane().add(imageEvenement);
        imageEvenement.setBounds(840, 230, 300, 300);

        imageName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageNameActionPerformed(evt);
            }
        });
        getContentPane().add(imageName);
        imageName.setBounds(410, 500, 150, 30);

        details.setText("Détails Evenement");
        details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsActionPerformed(evt);
            }
        });
        getContentPane().add(details);
        details.setBounds(1020, 560, 170, 30);

        Actualite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ActualiteMouseClicked(evt);
            }
        });
        getContentPane().add(Actualite);
        Actualite.setBounds(0, 120, 210, 40);

        Joueurs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JoueursMouseClicked(evt);
            }
        });
        getContentPane().add(Joueurs);
        Joueurs.setBounds(0, 160, 200, 40);

        Match.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MatchMouseClicked(evt);
            }
        });
        getContentPane().add(Match);
        Match.setBounds(0, 210, 200, 40);

        Club.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClubMouseClicked(evt);
            }
        });
        getContentPane().add(Club);
        Club.setBounds(0, 260, 200, 40);

        Tournoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TournoiMouseClicked(evt);
            }
        });
        getContentPane().add(Tournoi);
        Tournoi.setBounds(0, 310, 200, 40);

        MatchAmicale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MatchAmicaleMouseClicked(evt);
            }
        });
        getContentPane().add(MatchAmicale);
        MatchAmicale.setBounds(0, 360, 200, 40);

        GestionDopage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GestionDopageMouseClicked(evt);
            }
        });
        getContentPane().add(GestionDopage);
        GestionDopage.setBounds(0, 450, 200, 40);

        Stade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StadeMouseClicked(evt);
            }
        });
        getContentPane().add(Stade);
        Stade.setBounds(0, 410, 200, 40);

        Concours.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConcoursMouseClicked(evt);
            }
        });
        getContentPane().add(Concours);
        Concours.setBounds(0, 500, 210, 40);

        Formation8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Formation8MouseClicked(evt);
            }
        });
        getContentPane().add(Formation8);
        Formation8.setBounds(0, 540, 210, 40);

        article.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                articleMouseClicked(evt);
            }
        });
        getContentPane().add(article);
        article.setBounds(0, 590, 210, 30);

        Fond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/squad/ftt/images/event1.jpg"))); // NOI18N
        getContentPane().add(Fond);
        Fond.setBounds(0, -10, 1260, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed
        DefaultTableModel model = (DefaultTableModel) Evenement_Tab.getModel();
        EvenementDao eventDao = new EvenementDao();
        EvenementAdapter ea = new EvenementAdapter();
        System.out.println();
        eventDao.removeEvenementById(ea.evenements.get(Evenement_Tab.getSelectedRow()).getId_event());
        model.removeRow(Evenement_Tab.getSelectedRow());
    }//GEN-LAST:event_supprimerActionPerformed

    private void rechercheKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rechercheKeyReleased
        String query = recherche.getText();
        filter(query);
    }//GEN-LAST:event_rechercheKeyReleased

    private void Evenement_TabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Evenement_TabMouseClicked

        
        DefaultTableModel model = (DefaultTableModel) Evenement_Tab.getModel();
        libelleEvenement.setText(model.getValueAt(Evenement_Tab.getSelectedRow(), 0).toString());
        dateDebut.setDate((java.util.Date) model.getValueAt(Evenement_Tab.getSelectedRow(), 1));
        dateFin.setDate((java.util.Date) model.getValueAt(Evenement_Tab.getSelectedRow(), 2));
        EvenementAdapter ea = new EvenementAdapter(); 
       URL a=null;
        try {
            a = new URL("http://localhost/SquadWeb/web/uploads/"+ea.evenements.get(Evenement_Tab.getSelectedRow()).getImage());
        } catch (MalformedURLException ex) {
            Logger.getLogger(GestionEvenement.class.getName()).log(Level.SEVERE, null, ex);
        }
        ImageIcon i = new ImageIcon(a);
       Image img1 = i.getImage();  
       Image img2 = img1.getScaledInstance(imageEvenement.getWidth(), imageEvenement.getHeight(), Image.SCALE_SMOOTH);
        
        imageEvenement.setIcon(new ImageIcon(img2));
                 
      
        
    }//GEN-LAST:event_Evenement_TabMouseClicked

    private void ajouterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajouterMouseClicked
        evenement = new Evenement();
        JOptionPane jop3= new JOptionPane();
       Boolean b = true;
       java.util.Date utilDate = dateDebut.getDate();
        java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
        java.sql.Date sqlDate1 = new java.sql.Date(new java.util.Date( ).getTime());
        if(sqlDate.before(sqlDate1) ){
           JOptionPane.showMessageDialog(null,"Entrer une date valide a partir d'aujourd'hui");
           b=false;
        }
       if(libelleEvenement.getText().equals("")||((JTextField) dateDebut.getDateEditor().getUiComponent()).getText().equals(""))
       {     jop3.showMessageDialog(null, "Veuillez vérifier les champs", "Erreur", JOptionPane.ERROR_MESSAGE);  
       b=false;
       }
  long btwn= (Date.valueOf(((JTextField) dateFin.getDateEditor().getUiComponent()).getText()).getTime()- Date.valueOf(((JTextField) dateDebut.getDateEditor().getUiComponent()).getText()).getTime())/86400000 ;
   
      if( btwn< (Integer.parseInt((String) nbreJoueur.getSelectedItem()))/2 )
      { jop3.showMessageDialog(null, "Nombre de jours insuffisant pour "+Integer.parseInt((String) nbreJoueur.getSelectedItem())+" joueurs", "Erreur", JOptionPane.ERROR_MESSAGE); 
      b=false;
      }   
        if(b){
        evenement.setLibelle(libelleEvenement.getText());
        evenement.setNombreJoueur(Integer.parseInt((String) nbreJoueur.getSelectedItem()));
        evenement.setDate_debut(Date.valueOf(((JTextField) dateDebut.getDateEditor().getUiComponent()).getText()));
        evenement.setDate_fin(Date.valueOf(((JTextField) dateFin.getDateEditor().getUiComponent()).getText()));
        evenement.setSite((String) site.getSelectedItem());
        evenement.setType((String) type.getSelectedItem());
        evenement.setImage(imageNom);
        this.dispose();
        ChoixEvenement ge = new ChoixEvenement();
        ge.setSize(1220, 665);
        ge.setVisible(true);}
    }//GEN-LAST:event_ajouterMouseClicked

    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed


    }//GEN-LAST:event_ajouterActionPerformed

    private void modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierActionPerformed
        
        JOptionPane jop3 = new JOptionPane();
        DefaultTableModel model = (DefaultTableModel) Evenement_Tab.getModel();
        EvenementAdapter ea = new EvenementAdapter();
        EvenementDao eventDao = new EvenementDao();
        model.setValueAt(libelleEvenement.getText(), Evenement_Tab.getSelectedRow(), 0);
        model.setValueAt(Date.valueOf(((JTextField) dateDebut.getDateEditor().getUiComponent()).getText()), Evenement_Tab.getSelectedRow(), 1);
        model.setValueAt(Date.valueOf(((JTextField) dateFin.getDateEditor().getUiComponent()).getText()), Evenement_Tab.getSelectedRow(), 2);
        model.setValueAt((String) site.getSelectedItem(), Evenement_Tab.getSelectedRow(), 3);
        model.setValueAt((String) type.getSelectedItem(), Evenement_Tab.getSelectedRow(), 4);
        model.setValueAt((String) nbreJoueur.getSelectedItem(), Evenement_Tab.getSelectedRow(), 5);
        
        Evenement event = new Evenement(libelleEvenement.getText(),
                java.sql.Date.valueOf(((JTextField) dateDebut.getDateEditor().getUiComponent()).getText()),
                java.sql.Date.valueOf(((JTextField) dateDebut.getDateEditor().getUiComponent()).getText()),
                (String) site.getSelectedItem(),
                (String) type.getSelectedItem(),
                Integer.parseInt((String) nbreJoueur.getSelectedItem()));

        event.setId_event(ea.evenements.get(Evenement_Tab.getSelectedRow()).getId_event());
        eventDao.updateEvenement(event);


    }//GEN-LAST:event_modifierActionPerformed

    private void detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailsActionPerformed
    JOptionPane jop3= new JOptionPane();
         
       
        if(Evenement_Tab.getSelectedRow()==-1  )
    {
      jop3.showMessageDialog(null, "Veuillez selectionner un évenement", "Erreur", JOptionPane.ERROR_MESSAGE);
    }
        if(Evenement_Tab.getSelectedRow()!=-1  ){
        DefaultTableModel model = (DefaultTableModel) Evenement_Tab.getModel();
        EvenementDao eventDao = new EvenementDao();
        EvenementAdapter ea = new EvenementAdapter();
        evenement = new Evenement();
        evenement = eventDao.findEvenementById(ea.evenements.get(Evenement_Tab.getSelectedRow()).getId_event());
        model.removeRow(Evenement_Tab.getSelectedRow());
        AffichageEvenement ge = new AffichageEvenement();
        ge.setSize(986, 554);
        ge.setVisible(true);
    }
    }//GEN-LAST:event_detailsActionPerformed

    private void ajoutImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutImageActionPerformed

        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(null);
      if(fc.getSelectedFile()!=null)
      {File f = fc.getSelectedFile();
        String fileName = f.getAbsolutePath();
        imageName.setText(fileName);
        ImageIcon imgIcon = new ImageIcon(fileName);
        Image img1 = imgIcon.getImage();
        Image img2 = img1.getScaledInstance(imageEvenement.getWidth(), imageEvenement.getHeight(), Image.SCALE_SMOOTH);
        imageEvenement.setIcon(new ImageIcon(img2));
        filePath=imageName.getText();
        imageNom=f.getName();
      }
    }//GEN-LAST:event_ajoutImageActionPerformed

    private void imageNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imageNameActionPerformed

    private void ActualiteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActualiteMouseClicked

        this.dispose();
        AffichageActualite ge = new AffichageActualite();
        ge.setSize(1220, 655);
        ge.setVisible(true);
    }//GEN-LAST:event_ActualiteMouseClicked

    private void JoueursMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JoueursMouseClicked
        this.dispose();
        GestionJoueurs ge = new GestionJoueurs();
        ge.setSize(1220, 655);
        ge.setVisible(true);
    }//GEN-LAST:event_JoueursMouseClicked

    private void MatchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MatchMouseClicked
        this.dispose();
        GestionMatchs ge = new GestionMatchs();
        ge.setSize(1220, 655);
        ge.setVisible(true);
    }//GEN-LAST:event_MatchMouseClicked

    private void ClubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClubMouseClicked
        this.dispose();
        GestionClub ge = new GestionClub();
        ge.setSize(1220, 655);
        ge.setVisible(true);
    }//GEN-LAST:event_ClubMouseClicked

    private void TournoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TournoiMouseClicked
        this.dispose();
        GestionEvenement ge = new  GestionEvenement();
        ge.setSize(1220, 655);
        ge.setVisible(true);
    }//GEN-LAST:event_TournoiMouseClicked

    private void MatchAmicaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MatchAmicaleMouseClicked
        this.dispose();
        GestionArbitre ge = new GestionArbitre();
        ge.setSize(1220, 655);
        ge.setVisible(true);
    }//GEN-LAST:event_MatchAmicaleMouseClicked

    private void GestionDopageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GestionDopageMouseClicked
        this.dispose();
        GestionDopage ge = new GestionDopage();
        ge.setSize(1220, 655);
        ge.setVisible(true);
    }//GEN-LAST:event_GestionDopageMouseClicked

    private void StadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StadeMouseClicked
        this.dispose();
        GestionStade ge = new GestionStade();
        ge.setSize(1220, 655);
        ge.setVisible(true);
    }//GEN-LAST:event_StadeMouseClicked

    private void ConcoursMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConcoursMouseClicked
        this.dispose();
        GestionConcours ge = new GestionConcours();
        ge.setSize(1220, 655);
        ge.setVisible(true);
    }//GEN-LAST:event_ConcoursMouseClicked

    private void Formation8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Formation8MouseClicked
        this.dispose();
        GestionFormation ge = new GestionFormation();
        ge.setSize(1220, 655);
        ge.setVisible(true);
    }//GEN-LAST:event_Formation8MouseClicked

    private void articleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_articleMouseClicked
    this.dispose();
        AffichageArticles ge = new AffichageArticles();
        ge.setSize(1220, 655);
        ge.setVisible(true);
    }//GEN-LAST:event_articleMouseClicked



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionEvenement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionEvenement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionEvenement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionEvenement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GestionEvenement ge = new GestionEvenement();
                ge.setSize(1220, 665);
                ge.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Actualite;
    private javax.swing.JLabel Club;
    private javax.swing.JLabel Concours;
    private javax.swing.JTable Evenement_Tab;
    private javax.swing.JLabel Fond;
    private javax.swing.JLabel Formation8;
    private javax.swing.JLabel GestionDopage;
    private javax.swing.JLabel Joueurs;
    private javax.swing.JLabel Match;
    private javax.swing.JLabel MatchAmicale;
    private javax.swing.JLabel Stade;
    private javax.swing.JLabel Tournoi;
    private javax.swing.JButton ajoutImage;
    private javax.swing.JButton ajouter;
    private javax.swing.JLabel article;
    private com.toedter.calendar.JDateChooser dateDebut;
    private com.toedter.calendar.JDateChooser dateFin;
    private javax.swing.JButton details;
    private javax.swing.JLabel imageEvenement;
    private javax.swing.JTextField imageName;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField libelleEvenement;
    private javax.swing.JButton modifier;
    private javax.swing.JComboBox nbreJoueur;
    private javax.swing.JTextField recherche;
    private javax.swing.JComboBox site;
    private javax.swing.JButton supprimer;
    private javax.swing.JComboBox type;
    // End of variables declaration//GEN-END:variables
}
