/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package squad.ftt.gui;

import java.awt.Dimension;
import java.io.IOException;
import java.sql.Date;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import squad.ftt.dao.classes.concoursDAO;
import squad.ftt.entities.Concours;
import squad.ftt.adapters.Concourdapter;
import squad.ftt.dao.classes.UtilisateurDao;
import squad.ftt.entities.Utilisateur;

/**
 *
 * @author esprit
 */
public class GestionConcours extends javax.swing.JFrame {

    List<Concours> listeConcours;
    concoursDAO Cdao = new concoursDAO();
    Concours C = new Concours();

    public GestionConcours() {
        initComponents();
        Concourdapter concourAdapter = null;
        listeConcours = Cdao.DisplayAllConcours();
        concourAdapter = new Concourdapter();

        DefaultTableModel model = (DefaultTableModel) table_concours.getModel();
        Vector column_name = new Vector();
        Vector data_row = new Vector();
        System.out.println("aaaaa");
        for (int i = 0; i < concourAdapter.getColumnCount(); i++) {
            column_name.addElement(concourAdapter.getColumnName(i));
            model.setColumnIdentifiers(column_name);
        }
        for (int k = 0; k < concourAdapter.getRowCount(); k++) {
            data_row = new Vector();
            data_row.addElement(concourAdapter.getValueAt(k, 1));
            data_row.addElement(concourAdapter.getValueAt(k, 2));
            data_row.addElement(concourAdapter.getValueAt(k, 3));
            data_row.addElement(concourAdapter.getValueAt(k, 4));
            data_row.addElement(concourAdapter.getValueAt(k, 5));
            data_row.addElement(concourAdapter.getValueAt(k, 6));
            data_row.addElement(concourAdapter.getValueAt(k, 7));
            data_row.addElement(concourAdapter.getValueAt(k, 8));

            model.addRow(data_row);
        }
        table_concours.setModel(model);

    }

    public void filter(String query) {
        DefaultTableModel model = (DefaultTableModel) table_concours.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        table_concours.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(query));

    }

    /**
     *
     * @throws IOException
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Actualite = new javax.swing.JLabel();
        Joueurs = new javax.swing.JLabel();
        Match = new javax.swing.JLabel();
        Club = new javax.swing.JLabel();
        Tournoi = new javax.swing.JLabel();
        MatchAmicale = new javax.swing.JLabel();
        GestionDopage = new javax.swing.JLabel();
        Stade = new javax.swing.JLabel();
        Concours = new javax.swing.JLabel();
        Formation5 = new javax.swing.JLabel();
        article = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_concours = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_libelle_concour = new javax.swing.JTextField();
        site = new javax.swing.JTextField();
        description = new javax.swing.JTextField();
        frais = new javax.swing.JTextField();
        type = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_recherche = new javax.swing.JTextField();
        bouton_ajouter = new javax.swing.JButton();
        bouton_modifier = new javax.swing.JButton();
        bouton_supprimer = new javax.swing.JButton();
        txt_date_concour = new com.toedter.calendar.JDateChooser();
        date_deb = new com.toedter.calendar.JDateChooser();
        date_fin = new com.toedter.calendar.JDateChooser();
        GestionUsers = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Actualite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ActualiteMouseClicked(evt);
            }
        });
        getContentPane().add(Actualite);
        Actualite.setBounds(0, 120, 210, 40);

        Joueurs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JoueursMouseClicked(evt);
            }
        });
        getContentPane().add(Joueurs);
        Joueurs.setBounds(0, 160, 200, 40);

        Match.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MatchMouseClicked(evt);
            }
        });
        getContentPane().add(Match);
        Match.setBounds(0, 210, 200, 40);

        Club.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClubMouseClicked(evt);
            }
        });
        getContentPane().add(Club);
        Club.setBounds(0, 260, 200, 40);

        Tournoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TournoiMouseClicked(evt);
            }
        });
        getContentPane().add(Tournoi);
        Tournoi.setBounds(0, 310, 200, 40);

        MatchAmicale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MatchAmicaleMouseClicked(evt);
            }
        });
        getContentPane().add(MatchAmicale);
        MatchAmicale.setBounds(0, 360, 200, 40);

        GestionDopage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GestionDopageMouseClicked(evt);
            }
        });
        getContentPane().add(GestionDopage);
        GestionDopage.setBounds(0, 450, 200, 40);

        Stade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StadeMouseClicked(evt);
            }
        });
        getContentPane().add(Stade);
        Stade.setBounds(0, 410, 200, 40);

        Concours.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConcoursMouseClicked(evt);
            }
        });
        getContentPane().add(Concours);
        Concours.setBounds(0, 500, 210, 40);

        Formation5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Formation5MouseClicked(evt);
            }
        });
        getContentPane().add(Formation5);
        Formation5.setBounds(0, 540, 210, 40);
        getContentPane().add(article);
        article.setBounds(0, 590, 210, 30);

        table_concours.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        table_concours.setForeground(new java.awt.Color(102, 102, 255));
        table_concours.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Libellé","Date","Lieu","Description","Frais participation","Date deb depot","date fin depot","Type"
            }));
            table_concours.setGridColor(new java.awt.Color(51, 51, 255));
            table_concours.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    table_concoursMouseClicked(evt);
                }
            });
            jScrollPane1.setViewportView(table_concours);

            getContentPane().add(jScrollPane1);
            jScrollPane1.setBounds(250, 90, 910, 140);

            jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
            jLabel1.setForeground(new java.awt.Color(204, 204, 204));
            jLabel1.setText("Libellé:");
            getContentPane().add(jLabel1);
            jLabel1.setBounds(260, 260, 90, 17);

            jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
            jLabel2.setForeground(new java.awt.Color(204, 204, 204));
            jLabel2.setText("Date Concour:");
            getContentPane().add(jLabel2);
            jLabel2.setBounds(260, 300, 110, 20);

            jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
            jLabel3.setForeground(new java.awt.Color(204, 204, 204));
            jLabel3.setText("Site:");
            getContentPane().add(jLabel3);
            jLabel3.setBounds(260, 340, 60, 17);

            jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
            jLabel4.setForeground(new java.awt.Color(204, 204, 204));
            jLabel4.setText("Description:");
            getContentPane().add(jLabel4);
            jLabel4.setBounds(260, 380, 100, 17);

            jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
            jLabel5.setForeground(new java.awt.Color(204, 204, 204));
            jLabel5.setText("Frais participation:");
            getContentPane().add(jLabel5);
            jLabel5.setBounds(260, 420, 110, 17);

            jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
            jLabel6.setForeground(new java.awt.Color(204, 204, 204));
            jLabel6.setText("Date debut dépot:");
            getContentPane().add(jLabel6);
            jLabel6.setBounds(260, 460, 120, 17);

            jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
            jLabel7.setForeground(new java.awt.Color(204, 204, 204));
            jLabel7.setText("Date fin dépot:");
            getContentPane().add(jLabel7);
            jLabel7.setBounds(260, 500, 100, 17);

            jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
            jLabel8.setForeground(new java.awt.Color(204, 204, 204));
            jLabel8.setText("Type concour:");
            getContentPane().add(jLabel8);
            jLabel8.setBounds(260, 540, 100, 17);

            txt_libelle_concour.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    txt_libelle_concourActionPerformed(evt);
                }
            });
            getContentPane().add(txt_libelle_concour);
            txt_libelle_concour.setBounds(400, 250, 160, 30);
            getContentPane().add(site);
            site.setBounds(400, 330, 160, 30);
            getContentPane().add(description);
            description.setBounds(400, 370, 160, 30);
            getContentPane().add(frais);
            frais.setBounds(400, 410, 160, 30);
            getContentPane().add(type);
            type.setBounds(400, 530, 160, 30);

            jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
            jLabel9.setForeground(new java.awt.Color(204, 204, 204));
            jLabel9.setText("Recherche:");
            getContentPane().add(jLabel9);
            jLabel9.setBounds(900, 330, 80, 17);

            txt_recherche.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    txt_rechercheActionPerformed(evt);
                }
            });
            txt_recherche.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyReleased(java.awt.event.KeyEvent evt) {
                    txt_rechercheKeyReleased(evt);
                }
            });
            getContentPane().add(txt_recherche);
            txt_recherche.setBounds(980, 320, 150, 30);

            bouton_ajouter.setText("Ajouter");
            bouton_ajouter.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bouton_ajouterActionPerformed(evt);
                }
            });
            getContentPane().add(bouton_ajouter);
            bouton_ajouter.setBounds(750, 570, 69, 23);

            bouton_modifier.setText("Modifier");
            bouton_modifier.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bouton_modifierActionPerformed(evt);
                }
            });
            getContentPane().add(bouton_modifier);
            bouton_modifier.setBounds(850, 570, 71, 23);

            bouton_supprimer.setText("Supprimer");
            bouton_supprimer.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bouton_supprimerActionPerformed(evt);
                }
            });
            getContentPane().add(bouton_supprimer);
            bouton_supprimer.setBounds(950, 570, 81, 23);

            txt_date_concour.setDateFormatString("yyyy-MM-dd");
            getContentPane().add(txt_date_concour);
            txt_date_concour.setBounds(400, 290, 160, 30);

            date_deb.setDateFormatString("yyyy-MM-dd");
            getContentPane().add(date_deb);
            date_deb.setBounds(400, 450, 160, 30);

            date_fin.setDateFormatString("yyyy-MM-dd");
            getContentPane().add(date_fin);
            date_fin.setBounds(400, 490, 160, 30);

            GestionUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/squad/ftt/images/Dopage1.jpg"))); // NOI18N
            GestionUsers.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    GestionUsersMouseClicked(evt);
                }
            });
            getContentPane().add(GestionUsers);
            GestionUsers.setBounds(0, -10, 1260, 650);

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void ActualiteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActualiteMouseClicked

        this.dispose();
        AffichageActualite ge = new AffichageActualite();
        ge.setSize(1220, 655);
        ge.setVisible(true);
    }//GEN-LAST:event_ActualiteMouseClicked

    private void JoueursMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JoueursMouseClicked
        this.dispose();
        GestionJoueurs ge = new GestionJoueurs();
        ge.setSize(1220, 655);
        ge.setVisible(true);
    }//GEN-LAST:event_JoueursMouseClicked

    private void MatchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MatchMouseClicked
        this.dispose();
        GestionMatchs ge = new GestionMatchs();
        ge.setSize(1220, 655);
        ge.setVisible(true);
    }//GEN-LAST:event_MatchMouseClicked

    private void ClubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClubMouseClicked
        this.dispose();
        GestionClub ge = new GestionClub();
        ge.setSize(1220, 655);
        ge.setVisible(true);
    }//GEN-LAST:event_ClubMouseClicked

    private void TournoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TournoiMouseClicked
        this.dispose();
        GestionEvenement ge = new GestionEvenement();
        ge.setSize(1220, 655);
        ge.setVisible(true);
    }//GEN-LAST:event_TournoiMouseClicked

    private void MatchAmicaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MatchAmicaleMouseClicked
        this.dispose();
        GestionArbitre ge = new GestionArbitre();
        ge.setSize(1220, 655);
        ge.setVisible(true);
    }//GEN-LAST:event_MatchAmicaleMouseClicked

    private void GestionDopageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GestionDopageMouseClicked
        this.dispose();
        GestionDopage ge = new GestionDopage();
        ge.setSize(1220, 655);
        ge.setVisible(true);
    }//GEN-LAST:event_GestionDopageMouseClicked

    private void StadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StadeMouseClicked
        this.dispose();
        GestionStade ge = new GestionStade();
        ge.setSize(1220, 655);
        ge.setVisible(true);
    }//GEN-LAST:event_StadeMouseClicked

    private void ConcoursMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConcoursMouseClicked
        this.dispose();
        GestionConcours ge = new GestionConcours();
        ge.setSize(1220, 655);
        ge.setVisible(true);
    }//GEN-LAST:event_ConcoursMouseClicked

    private void Formation5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Formation5MouseClicked
        this.dispose();
        GestionFormation ge = new GestionFormation();
        ge.setSize(1220, 655);
        ge.setVisible(true);
    }//GEN-LAST:event_Formation5MouseClicked

    private void txt_libelle_concourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_libelle_concourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_libelle_concourActionPerformed

    private void table_concoursMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_concoursMouseClicked
//       int idc = (int) table_concours.getValueAt(table_concours.getSelectedRow(), 0);
//        C = Cdao.findConcoursById(idc);
//        String F = String.valueOf(C.getFrais_participation());
//       
//        txt_libelle_concour.setText(C.getLibelle_concour());
//        txt_date_concour.setDate(C.getDate_debut_concour());
//        site.setText(C.getLieu_concour());
//        description.setText(C.getDescription_concours());
//        frais.setText(F);
//        date_deb.setDate(C.getDate_debut_depot());
//        date_fin.setDate(C.getDate_fin_depot());
//        type.setText(C.getType_concour());

        DefaultTableModel model = (DefaultTableModel) table_concours.getModel();

        txt_libelle_concour.setText(model.getValueAt(table_concours.getSelectedRow(), 0).toString());
        txt_date_concour.setDate((java.util.Date) model.getValueAt(table_concours.getSelectedRow(), 1));
        site.setText(model.getValueAt(table_concours.getSelectedRow(), 2).toString());
        description.setText(model.getValueAt(table_concours.getSelectedRow(), 3).toString());
        frais.setText(model.getValueAt(table_concours.getSelectedRow(), 4).toString());
        date_deb.setDate((java.util.Date) model.getValueAt(table_concours.getSelectedRow(), 5));
        date_fin.setDate((java.util.Date) model.getValueAt(table_concours.getSelectedRow(), 6));
        type.setText(model.getValueAt(table_concours.getSelectedRow(), 7).toString());
    }//GEN-LAST:event_table_concoursMouseClicked

    private void bouton_ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_ajouterActionPerformed
        concoursDAO concours = new concoursDAO();
        Concours c = new Concours();

        if (txt_libelle_concour.getText().equals("")
                | txt_date_concour.getDate() == null
                | site.getText().equals("")
                | description.getText().equals("")
                | frais.getText().equals("")
                | date_deb.getDate() == null
                | date_fin.getDate() == null
                | type.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs");
        } else {
            c.setLibelle_concour(txt_libelle_concour.getText());
            c.setDate_debut_concour(Date.valueOf(((JTextField) txt_date_concour.getDateEditor().getUiComponent()).getText()));
            c.setLieu_concour(site.getText());
            c.setDescription_concours(description.getText());
            c.setFrais_participation(Float.parseFloat(frais.getText()));
            c.setDate_debut_depot(Date.valueOf(((JTextField) date_deb.getDateEditor().getUiComponent()).getText()));
            c.setDate_fin_depot(Date.valueOf(((JTextField) date_fin.getDateEditor().getUiComponent()).getText()));
            c.setType_concour(type.getText());
            
            int rep = JOptionPane.showConfirmDialog(null, "Etes vous sur de vouloir ajouter cet utilisateur?", "Attention", JOptionPane.YES_NO_OPTION);
            if (rep == JOptionPane.YES_OPTION) {
                
            }
            concours.ajouterConcours(c);

            JOptionPane.showMessageDialog(null, "Un concours a été ajouté avec succès");

            DefaultTableModel model = (DefaultTableModel) table_concours.getModel();
            model.addRow(new Object[]{txt_libelle_concour.getText(), Date.valueOf(((JTextField) txt_date_concour.getDateEditor().getUiComponent()).getText()), site.getText(), description.getText(), frais.getText(), Date.valueOf(((JTextField) date_deb.getDateEditor().getUiComponent()).getText()), Date.valueOf(((JTextField) date_fin.getDateEditor().getUiComponent()).getText()), type.getText()});

            txt_libelle_concour.setText("");
            txt_date_concour.setDateFormatString("");
            site.setText("");
            description.setText("");
            frais.setText("");
            date_deb.setDateFormatString("");
            date_fin.setDateFormatString("");
            type.setText("");

            //java.util.Date utilDate = Date.();
            //java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
            //u. setDate_naiss(sqlDate);
        }


                                                  }//GEN-LAST:event_bouton_ajouterActionPerformed

    private void txt_rechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rechercheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rechercheActionPerformed

    private void txt_rechercheKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_rechercheKeyReleased
        String query = txt_recherche.getText().toLowerCase();
        filter(query);
    }//GEN-LAST:event_txt_rechercheKeyReleased

    private void bouton_modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_modifierActionPerformed
        DefaultTableModel model = (DefaultTableModel) table_concours.getModel();

        model.setValueAt(txt_libelle_concour.getText(), table_concours.getSelectedRow(), 0);
        model.setValueAt(java.sql.Date.valueOf(((JTextField) txt_date_concour.getDateEditor().getUiComponent()).getText()), table_concours.getSelectedRow(), 1);
        model.setValueAt(site.getText(), table_concours.getSelectedRow(), 2);
        model.setValueAt(description.getText(), table_concours.getSelectedRow(), 3);
        model.setValueAt(frais.getText(), table_concours.getSelectedRow(), 4);
        model.setValueAt(java.sql.Date.valueOf(((JTextField) date_deb.getDateEditor().getUiComponent()).getText()), table_concours.getSelectedRow(), 5);
        model.setValueAt(java.sql.Date.valueOf(((JTextField) date_fin.getDateEditor().getUiComponent()).getText()), table_concours.getSelectedRow(), 6);
        model.setValueAt(type.getText(), table_concours.getSelectedRow(), 7);

        Concours c = new Concours();
        c.setLibelle_concour(txt_libelle_concour.getText());
        c.setDate_debut_concour(java.sql.Date.valueOf(((JTextField) txt_date_concour.getDateEditor().getUiComponent()).getText()));
        c.setLieu_concour(site.getText());
        c.setDescription_concours(description.getText());
        c.setFrais_participation(Float.parseFloat(frais.getText()));
        c.setDate_debut_depot(java.sql.Date.valueOf(((JTextField) date_deb.getDateEditor().getUiComponent()).getText()));
        c.setDate_fin_depot(java.sql.Date.valueOf(((JTextField) date_fin.getDateEditor().getUiComponent()).getText()));
        c.setType_concour(type.getText());
        
          
        int id_concour;
        id_concour = (int) listeConcours.get(table_concours.getSelectedRow()).getId_Concour();
        concoursDAO concoursDao = new concoursDAO();
        concoursDao.modifierConcours(c, id_concour);
    
            JOptionPane.showMessageDialog(null, "modification effectué avec succès");    }//GEN-LAST:event_bouton_modifierActionPerformed
 
    private void bouton_supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_supprimerActionPerformed
         
                
        
        DefaultTableModel model = (DefaultTableModel) table_concours.getModel();
        concoursDAO concoursDao = new concoursDAO();
        concoursDao.deleteConcours(listeConcours.get(table_concours.getSelectedRow()).getId_Concour());
        model.removeRow(table_concours.getSelectedRow());
            JOptionPane.showMessageDialog(null, "Suppression effectuée");    }//GEN-LAST:event_bouton_supprimerActionPerformed

    private void GestionUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GestionUsersMouseClicked
        this.dispose();
       GestionUtilisateurs gu = new GestionUtilisateurs();
        gu.setSize(1220, 655);
        gu.setVisible(true);
    }//GEN-LAST:event_GestionUsersMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionConcours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionConcours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionConcours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionConcours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GestionConcours ge = new GestionConcours();
                ge.setSize(1220, 665);
                ge.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Actualite;
    private javax.swing.JLabel Club;
    private javax.swing.JLabel Concours;
    private javax.swing.JLabel Formation5;
    private javax.swing.JLabel GestionDopage;
    private javax.swing.JLabel GestionUsers;
    private javax.swing.JLabel Joueurs;
    private javax.swing.JLabel Match;
    private javax.swing.JLabel MatchAmicale;
    private javax.swing.JLabel Stade;
    private javax.swing.JLabel Tournoi;
    private javax.swing.JLabel article;
    private javax.swing.JButton bouton_ajouter;
    private javax.swing.JButton bouton_modifier;
    private javax.swing.JButton bouton_supprimer;
    private com.toedter.calendar.JDateChooser date_deb;
    private com.toedter.calendar.JDateChooser date_fin;
    private javax.swing.JTextField description;
    private javax.swing.JTextField frais;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField site;
    private javax.swing.JTable table_concours;
    private com.toedter.calendar.JDateChooser txt_date_concour;
    private javax.swing.JTextField txt_libelle_concour;
    private javax.swing.JTextField txt_recherche;
    private javax.swing.JTextField type;
    // End of variables declaration//GEN-END:variables
}
