/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package squad.ftt.gui;

import java.awt.Frame;
import java.sql.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import squad.ftt.dao.classes.UtilisateurDao;
import squad.ftt.entities.Utilisateur;

/**
 *
 * @author hp
 */
public class Inscription extends javax.swing.JFrame {

    /**
     * Creates new form Inscription
     */
    public Inscription() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cin_insc = new javax.swing.JTextField();
        nation_insc = new javax.swing.JTextField();
        nom_insc = new javax.swing.JTextField();
        tel_insc = new javax.swing.JTextField();
        mail_insc = new javax.swing.JTextField();
        username_insc = new javax.swing.JTextField();
        prenom_insc = new javax.swing.JTextField();
        insc_button = new javax.swing.JButton();
        datenaiss_insc = new com.toedter.calendar.JDateChooser();
        passwd_insc = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cin_insc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cin_inscActionPerformed(evt);
            }
        });
        getContentPane().add(cin_insc, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 155, 240, 30));
        getContentPane().add(nation_insc, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 235, 240, 30));
        getContentPane().add(nom_insc, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 240, 30));
        getContentPane().add(tel_insc, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 240, 30));
        getContentPane().add(mail_insc, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 240, 30));
        getContentPane().add(username_insc, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 240, 30));
        getContentPane().add(prenom_insc, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 240, 30));

        insc_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/squad/ftt/images/sign up b copy.jpg"))); // NOI18N
        insc_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insc_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(insc_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 483, 350, 50));
        getContentPane().add(datenaiss_insc, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 195, 240, 30));

        passwd_insc.setText("jPasswordField1");
        getContentPane().add(passwd_insc, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 240, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/squad/ftt/images/sign up.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(960, 640));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cin_inscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cin_inscActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cin_inscActionPerformed

    private void insc_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insc_buttonActionPerformed
        UtilisateurDao us = new UtilisateurDao();
        Utilisateur u = new Utilisateur();
        
         if (
        nom_insc.getText().equals("") 
        | prenom_insc.getText().equals("")
        |cin_insc.getText().equals("")
        |datenaiss_insc.getDate()==null
        |nation_insc.getText().equals("")
        |tel_insc.getText().equals("")
        |mail_insc.getText().equals("")
        |username_insc.getText().equals("")
        |passwd_insc.getPassword().toString().equals("")
        )
         {
             
     JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs");
        }
 else if (! mail_insc.getText().matches("^[a-zA-Z0-9\\.\\-\\_]+@([a-zA-Z0-9\\-\\_\\.]+\\.)+([a-zA-Z]{2,4})$")){
		  JOptionPane.showMessageDialog(null, "Le mail doit contenir un @ ");
        }
 else {
     
     java.util.Date utildate = datenaiss_insc.getDate();
            java.sql.Date sqlDate = new java.sql.Date(utildate.getTime());
            
        u.setNom(nom_insc.getText());
        u.setPrenom(prenom_insc.getText());        
        u.setCin_user(Float.parseFloat(cin_insc.getText()));
        u.setDate_de_naissance(sqlDate);
        u.setNationaliter(nation_insc.getText());
        u.setTel(Float.parseFloat(tel_insc.getText()));
        u.setEmail(mail_insc.getText());
        u.setUsername(username_insc.getText());
        u.setPassword(passwd_insc.getText());
        u.setRole("fan");
        
        us.Inscription(u);
        
        JOptionPane.showMessageDialog(null, "Inscription effectuée avec succès");
        

        nom_insc.setText("");
        prenom_insc.setText("");
        cin_insc.setText("");
        datenaiss_insc.setDateFormatString("");
        nation_insc.setText("");
        tel_insc.setText("");
        prenom_insc.setText("");
        nom_insc.setText("");
        passwd_insc.setText("");
        
        Authentification auth = new Authentification();
        auth.setVisible(true);
        this.dispose();
        //java.util.Date utilDate = Date.();
        //java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
        //u. setDate_naiss(sqlDate);

    }//GEN-LAST:event_insc_buttonActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inscription().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cin_insc;
    private com.toedter.calendar.JDateChooser datenaiss_insc;
    private javax.swing.JButton insc_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField mail_insc;
    private javax.swing.JTextField nation_insc;
    private javax.swing.JTextField nom_insc;
    private javax.swing.JPasswordField passwd_insc;
    private javax.swing.JTextField prenom_insc;
    private javax.swing.JTextField tel_insc;
    private javax.swing.JTextField username_insc;
    // End of variables declaration//GEN-END:variables
}
